"""initial_tables

Revision ID: a05ce7ebcfa2
Revises: 
Create Date: 2026-06-20 22:54:52.556511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a05ce7ebcfa2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claims',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('member_id', sa.String(length=50), nullable=False),
    sa.Column('policy_id', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('claimed_amount', sa.Float(), nullable=False),
    sa.Column('treatment_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hospital_name', sa.String(length=200), nullable=True),
    sa.Column('pre_auth_obtained', sa.Boolean(), nullable=False),
    sa.Column('simulate_component_failure', sa.Boolean(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('idempotency_key', name='uq_claims_idempotency_key')
    )
    op.create_index(op.f('ix_claims_member_id'), 'claims', ['member_id'], unique=False)
    op.create_table('claim_traces',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('claim_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('trace_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_traces_claim_id'), 'claim_traces', ['claim_id'], unique=True)
    op.create_table('decisions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('claim_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('approved_amount', sa.Float(), nullable=False),
    sa.Column('reasons_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('checks_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('degraded', sa.Boolean(), nullable=False),
    sa.Column('degradation_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_claim_id'), 'decisions', ['claim_id'], unique=True)
    op.create_table('documents',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('claim_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('file_id', sa.String(length=100), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=True),
    sa.Column('declared_type', sa.String(length=50), nullable=True),
    sa.Column('classified_type', sa.String(length=50), nullable=True),
    sa.Column('classification_confidence', sa.Float(), nullable=True),
    sa.Column('quality_flag', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_claim_id'), 'documents', ['claim_id'], unique=False)
    op.create_table('extractions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('document_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('extracted_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('provider_name', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('extractions')
    op.drop_index(op.f('ix_documents_claim_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_decisions_claim_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_claim_traces_claim_id'), table_name='claim_traces')
    op.drop_table('claim_traces')
    op.drop_index(op.f('ix_claims_member_id'), table_name='claims')
    op.drop_table('claims')
    # ### end Alembic commands ###
